version: 2
updates:
  # Enable version updates for mix
  - package-ecosystem: "mix"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "weekly"
    labels:
      - "dependabot-update"
