name: CI checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  MIX_ENV: test

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir: [1.11.x]
        otp: [23.x]
    name: Check Code Quality
    steps:
      - uses: actions/checkout@v2

      - uses: erlef/setup-beam@v1
        id: beam
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}

      - name: Retrieve Build Cache
        uses: actions/cache@v3
        id: build-folder-cache
        with:
          path: _build
          key: ${{ runner.os }}-${{ steps.beam.outputs.otp-version }}-${{ steps.beam.outputs.elixir-version }}-build-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - name: Retrieve Mix Dependencies Cache
        uses: actions/cache@v3
        id: deps-cache
        with:
          path: deps
          key: ${{runner.os}}-${{steps.beam.outputs.otp-version}}-${{steps.beam.outputs.elixir-version}}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      # Copied from the example on https://github.com/jeremyjh/dialyxir/blob/master/README.md#github-actions
      - name: Restore PLT Cache
        uses: actions/cache@v3
        id: plt_cache
        with:
          key: |
            ${{ runner.os }}-${{ steps.beam.outputs.elixir-version }}-${{ steps.beam.outputs.otp-version }}-plt
          restore-keys: |
            ${{ runner.os }}-${{ steps.beam.outputs.elixir-version }}-${{ steps.beam.outputs.otp-version }}-plt
          path: |
            priv/plts

      - name: Install Mix Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get

      # something in 1.10.2 isn't formatted, but is in 1.10.4
      # - name: Check Formatting
      #   run: mix format --check-formatted

      - name: Run Credo
        run: mix credo --strict

      - name: Run Coverage
        run: mix coveralls.json

      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          files: ./cover/excoveralls.json

      # Create PLTs if no cache was found
      - name: Create PLTs
        if: steps.plt_cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p priv/plts
          mix dialyzer

      - name: Run dialyzer
        run: mix dialyzer --format github
