name: mix test for [version matrix]

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-20.04
    name: Test - OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      # see https://hexdocs.pm/elixir/1.14.0-rc.0/compatibility-and-deprecations.html#compatibility-between-elixir-and-erlang-otp
      matrix:
        otp: ["22.x", "23.x", "24.x", "25.x"]
        elixir: ["1.10.x", "1.11.x", "1.12.x", "1.13.x", "1.14.x"]
        exclude:
          # OTP 22
          - elixir: "1.14.x"
            otp: "22.x"
          # OTP 23
          - elixir: "1.10.x"
            otp: "23.x"
          # OTP 24
          - elixir: "1.10.x"
            otp: "24.x"
          - elixir: "1.11.x"
            otp: "24.x"
          # OTP 25
          - elixir: "1.10.x"
            otp: "25.x"
          - elixir: "1.11.x"
            otp: "25.x"
          - elixir: "1.12.x"
            otp: "25.x"
          - elixir: "1.13.x"
            otp: "25.x"
        include:
          - elixir: "1.13.4"
            otp: "25.x"
    steps:
      - uses: actions/checkout@v1.0.0

      - uses: erlef/setup-beam@v1
        id: beam
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}

      - name: Retrieve Build Cache
        uses: actions/cache@v3
        id: build-folder-cache
        with:
          path: _build
          key: ${{ runner.os }}-${{ steps.beam.outputs.otp-version}}-${{steps.beam.outputs.elixir-version }}-build-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - name: Retrieve Mix Dependencies Cache
        uses: actions/cache@v3
        id: deps-cache
        with:
          path: deps
          key: ${{runner.os}}-${{steps.beam.outputs.otp-version}}-${{steps.beam.outputs.elixir-version}}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - run: mix local.rebar --force
      - run: mix local.hex --force
      - run: mix deps.get
      - run: mix compile --warnings-as-errors
      - run: mix test
